jobs:
  build:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            python manage.py test taskManager

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
          continue-on-error: true

  artifact:
    docker:
      - image: python:3.6
    steps:
      - name: Create artifact file
        run: echo "hello" > hello.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: hello.txt

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step"

workflows:
  version: 2
  django:
    jobs:
      - build
      - test
      - integration
      - artifact  # Added the new 'artifact' job
      - prod
